### ISSUE TITLE
rings are too fussy about orientation - should bond every 20 degrees and also upside down

### ISSUE THREAD

**Issue by neon-ninja** [UoA-eResearch/prx_fishtank#26]
this would seemingly require donors to be able to bond to other donors in our current setup... @ddoak thoughts?

**Comment by ddoak** [comment]
Yes. Short answer is that all the work making them fussy about acceptors and donors was not necessary

:-(

At the moment the rings only stack like this (parallel):
a->d  a->d

But they should also stack like this (antiparallel):
a->d   d<-a
d<-a   a->d

However, it would probably be best if we could allow the additional anitparallel stacking to be switchable on/off in the code because it is the degenerate simpler case. i.e. going forward looking at other assemblies the "parallel only" code / logic is likely to be useful.

**Comment by ddoak** [comment]
Re 20 degrees.

The relative rotation of the rings is currently constrained to one transform  (+8 degrees)  (derived from the 'master' dimers in the prefab).
As discussed the symmetry (6 x dimers / 12 x monomers) within the ring allows for other docking rotations.

I'm not sure about the 20 degrees though. 

i.e. given the symmetry I would have expected there to be either 60 degree  (360/6) or 30 degree (360/12) difference in the docking rotations. 

We need some more information from Juliet / Amy.

**Comment by ddoak** [comment]
Juliet sent me this image - which is pertinent.

(Note that it is it is from the earlier paper describing a slightly different crystal structure - in which the ring structure was comprised of 5 dimers = 10 monomers)

If the ring schematic in the lower diagram was was flipped 180 degrees then monomer A would map to the T position and K would map to the J position. So an antiparallel (180 flipped) ring could dock in the stack.

![image](https://user-images.githubusercontent.com/7423291/37738491-153166f6-2d4f-11e8-97d1-0ab2c858a31d.png)

**Comment by ddoak** [comment]
Checked with Juliet and Amy today 

For the ring rotations the relative angles are:

(n x 60) + 8 degree rotations [where n is 0,1,2,3,4,5]
